version: '3'

services:
  redis-stack:
    image: "redis/redis-stack:latest"
    restart: unless-stopped
    container_name: redis-stack
    volumes:
      - C:\var\log\docker\redis:/data
    networks:
      - app-net
    ports:
      - 6379:6379
      - 8001:8001
networks:
  app-net:
    driver: bridge
